name: flutter_course
description: Instagram clone
publish_to: 'none'
version: 0.0.1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  pedantic: ^1.9.2

  # firebase
  firebase_core: any

  # flutter
  flutter_redux: any

  # dart
  redux: any
  redux_epics: any
  rxdart: any
  built_value: any
  built_collection: any
  freezed_annotation: any
  http: any

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: any
  built_value_generator: any
  freezed: any

dependency_overrides:
  rxdart: ^0.25.0
  analyzer: 0.41.1

flutter:
  uses-material-design: true
