name: flutter_course
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  pedantic: ^1.9.2
  http: any
  built_value: ^7.1.0
  built_collection: ^4.3.2
  redux: ^4.0.0+3
  flutter_redux: ^0.7.0
  freezed_annotation: any
  flutter_staggered_grid_view: ^0.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.9
  built_value_generator: ^7.1.0
  freezed: ^0.12.6

dependency_overrides:
  analyzer: 0.41.1

flutter:
  uses-material-design: true
